apiVersion: v1
kind: Pod
metadata:
  name: log-processor
spec:
  containers:
    - name: nginx  
      image: nginx:1.20
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html   

    - name: busybox
      image: busybox
      command: ['/bin/sh', '-c']
      args:
        - while true; do
            date >> /shared/access.log;
            sleep 5;
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /shared

  volumes:
    - name: shared-logs
      emptyDir: {}
