apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev-deployment
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - myapp
    - key: env
      operator: In
      values:
      - dev
    - key: tier
      operator: In
      values:
      - backend
  template:
    metadata:
      labels:
        app: myapp
        env: dev
        tier: backend
    spec:
      containers:
      - name: my-backend
        image: my-backend:latest
        ports:
        - containerPort: 8080
