apiVersion: v1
kind: Pod
metadata:
  name: pod-manual-1
  labels:
    app: test
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-manual-2
  labels:
    app: test
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx
