apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
      version: v1
  template:
    metadata:
      labels:
        app: pilotnew
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx
