
apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
