apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-dev
  labels:
    app: myapp
    tier: backend
    env: prod
    component: express-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: backend
      env: prod
  template:
    metadata:
      labels:
        app: myapp
        tier: backend
        env: prod
        component: express-api
    spec:
      containers:
      - name: api-server
        image: nginx
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-backend-service-dev
  labels:
    app: myapp
    tier: backend
    env: prod
spec:
  selector:
    app: myapp
    tier: backend
    env: prod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
