apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-dev
  labels:
    app: myapp
    tier: database
    env: staging
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      tier: database
      env: staging
  template:
    metadata:
      labels:
        app: myapp
        tier: database
        env: staging
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service-dev
  labels:
    app: myapp
    tier: database
    env: staging
spec:
  selector:
    app: myapp
    tier: database
    env: staging
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
