apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-dev
  labels:
    app: myapp
    tier: frontend
    env: dev
    component: react-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: frontend
      env: dev
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
        env: dev
        component: react-ui
    spec:
      containers:
      - name: react-app
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service-dev
  labels:
    app: myapp
    tier: frontend
    env: dev
spec:
  selector:
    app: myapp
    tier: frontend
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80




